### ISSUE TITLE
现在的版本不能在线看PDF和epub了么

### ISSUE THREAD

**Issue by yunzhongci** [Technosoft2000/docker-calibre-web#65] opened 2019-07-29 02:57 UTC
现在的版本不能在线看PDF和epub了么？为什么我找不到在线看的按钮了？

**Comment by Technosoft2000** [comment] 2019-08-04 18:30
Please write in future in English, otherwise I'll close the issue immediately!

Google translation of your question is:
**Can't the current version see PDF and epub online? Why can't I find the button to watch online?**

I've the current version 0.6.4 of Calibre Web in my Docker container where the uploaded epub and converted pdf can be viewed with the "Read in browser" button without any problems - I use Google Chrome as browser. Klick on the Calibre Web on a book and then you should see the "Read in browser" button, which will open a submenu where you can select the uploaded epub or pdf file to directly read it in the browser.

By the way if you've any further questions about the application go to the application project of Calibre Web at https://github.com/janeczku/calibre-web/

I'm not the developer of the application, I provide only the Docker Image which can run the application inside it.

**Comment by mengqingmeng** [comment] 2019-08-12 00:39
I can't read online as well,there is no read in browser button,i'am using chrome browser(76.0.3809.100 version).It cant be read online before.what's the problem?

**Comment by Technosoft2000** [comment] 2019-08-12 14:34
I can reproduce the issue with the latest version of Calibre-Web, I'll have a look at https://github.com/janeczku/calibre-web/ what was changed and will update the docker image if necessary.

**Comment by Technosoft2000** [comment] 2019-08-12 19:32
The new version of Calibre-Web has now an additional permission for the Ebook Viewer (Read Button) so you've to enable the permission for every user to get the read button.

Look here at the pictures:

Permission is disabled by default:
![01_Admin_View_Ebooks_Not_Enabled](https://user-images.githubusercontent.com/1690853/62892234-07f06200-bd48-11e9-8261-388f679f07b5.png)

Enable the permission:
![02_Admin_View_Ebooks_Not_Enabled_No_Read_Button](https://user-images.githubusercontent.com/1690853/62892243-0aeb5280-bd48-11e9-9f9f-670e40b0fdb7.png)

No Read Button availaible because the user has no permission for it:
![03_Admin_has_no_right_to_view_books](https://user-images.githubusercontent.com/1690853/62892248-0de64300-bd48-11e9-8ae1-287d81002a1d.png)

Enable the permission and don't forget to press the Submit button:
![04_Admin_enable_right_to_view_books](https://user-images.githubusercontent.com/1690853/62892249-10489d00-bd48-11e9-8c62-d70f0d5ba3e7.png)

Permisson is now active:
![05_Admin_right_to_view_books_enabled](https://user-images.githubusercontent.com/1690853/62892251-13438d80-bd48-11e9-8217-8e66b19a45a1.png)

The Read Button get's visible because the user has the permission:
![06_Admin_has_Read_button_available](https://user-images.githubusercontent.com/1690853/62892258-1b033200-bd48-11e9-8d3f-4b05366bd925.png)

Please check for such things in future the Calibre-Web application site and the Wiki of it:
https://github.com/janeczku/calibre-web/

**Comment by mengqingmeng** [comment] 2019-08-13 01:03
> The new version of Calibre-Web has now an additional permission for the Ebook Viewer (Read Button) so you've to enable the permission for every user to get the read button.
> 
> Look here at the pictures:
> 
> Permission is disabled by default:
> ![01_Admin_View_Ebooks_Not_Enabled](https://user-images.githubusercontent.com/1690853/62892234-07f06200-bd48-11e9-8261-388f679f07b5.png)
> 
> Enable the permission:
> ![02_Admin_View_Ebooks_Not_Enabled_No_Read_Button](https://user-images.githubusercontent.com/1690853/62892243-0aeb5280-bd48-11e9-9f9f-670e40b0fdb7.png)
> 
> No Read Button availaible because the user has no permission for it:
> ![03_Admin_has_no_right_to_view_books](https://user-images.githubusercontent.com/1690853/62892248-0de64300-bd48-11e9-8ae1-287d81002a1d.png)
> 
> Enable the permission and don't forget to press the Submit button:
> ![04_Admin_enable_right_to_view_books](https://user-images.githubusercontent.com/1690853/62892249-10489d00-bd48-11e9-8c62-d70f0d5ba3e7.png)
> 
> Permisson is now active:
> ![05_Admin_right_to_view_books_enabled](https://user-images.githubusercontent.com/1690853/62892251-13438d80-bd48-11e9-8217-8e66b19a45a1.png)
> 
> The Read Button get's visible because the user has the permission:
> ![06_Admin_has_Read_button_available](https://user-images.githubusercontent.com/1690853/62892258-1b033200-bd48-11e9-8d3f-4b05366bd925.png)
> 
> Please check for such things in future the Calibre-Web application site and the Wiki of it:
> https://github.com/janeczku/calibre-web/

thanks a lot

**Comment by mengqingmeng** [comment] 2019-08-13 01:04
@Technosoft2000 thanks a lot

**Closed** 2019-12-16 21:18 UTC
Labels: question

**Comment by sliot1** [comment] 2021-11-18 06:30
Hello, I installed the above method and operated it, but it is still not supported. Read online

**Comment by real-jiakai** [comment] 2022-07-11 11:51
> The new version of Calibre-Web has now an additional permission for the Ebook Viewer (Read Button) so you've to enable the permission for every user to get the read button.
> 
> 新版本的 Calibre-Web 现在对电子书浏览器(阅读按钮)有了额外的权限，所以你必须允许每个用户获得阅读按钮的权限。
> 
> Look here at the pictures:
> 
> 看看这些照片:
> 
> Permission is disabled by default: ![01_Admin_View_Ebooks_Not_Enabled](https://user-images.githubusercontent.com/1690853/62892234-07f06200-bd48-11e9-8261-388f679f07b5.png)
> 
> 默认情况下禁用权限:
> 
> Enable the permission: ![02_Admin_View_Ebooks_Not_Enabled_No_Read_Button](https://user-images.githubusercontent.com/1690853/62892243-0aeb5280-bd48-11e9-9f9f-670e40b0fdb7.png)
> 
> 启用许可:
> 
> No Read Button availaible because the user has no permission for it: ![03_Admin_has_no_right_to_view_books](https://user-images.githubusercontent.com/1690853/62892248-0de64300-bd48-11e9-8ae1-287d81002a1d.png)
> 
> 没有“读取按钮”可用，因为用户没有该按钮的权限:
> 
> Enable the permission and don't forget to press the Submit button: ![04_Admin_enable_right_to_view_books](https://user-images.githubusercontent.com/1690853/62892249-10489d00-bd48-11e9-8c62-d70f0d5ba3e7.png)
> 
> 启用权限并且不要忘记按下 Submit 按钮:
> 
> Permisson is now active: ![05_Admin_right_to_view_books_enabled](https://user-images.githubusercontent.com/1690853/62892251-13438d80-bd48-11e9-8217-8e66b19a45a1.png)
> 
> Permisson 现在处于活动状态:
> 
> The Read Button get's visible because the user has the permission: ![06_Admin_has_Read_button_available](https://user-images.githubusercontent.com/1690853/62892258-1b033200-bd48-11e9-8d3f-4b05366bd925.png)
> 
> Read Button get 是可见的，因为用户拥有以下权限:
> 
> Please check for such things in future the Calibre-Web application site and the Wiki of it: https://github.com/janeczku/calibre-web/
> 
> 以后请查看 Calibre-Web 应用程序网站及其维基 https://github.com/janeczku/Calibre-Web/

Nice.❤️❤️❤️
